<%= appName %>:
  container_name: <%= appName %>
  command: "<%= appName %>/loc"
  image: "<%= dockerRepo %>/framework/<%= appName %>:0.0.1
  links:
    - mongo
  ports:
    - "9000:9000"
  environment:
    CONSUL: <%= consulRepo %>

mongo:
  container_name: genesis-mongo
  command: '--smallfiles --dbpath=/tmp'
  ports:
    - "27017:27017"
  image: <%= dockerRepo %>/mongo:latest
